name: nicholastennison
favicon: null
layout_spectrum: 0.90631
typography_spectrum: 0.68202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00441e'
    - '#00622b'
    - '#231806'
    - '#009b37'
  brandStrength: 0
  lightness: 0.8753172596916556
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
